version: "3"
services:
  routed_10:
    build: .
    stdin_open: true
    tty: true
    command:
      - "./routed"
      - "172.16.238.10"
      - "/file_dir"
      - "link_list=/topo/links_10.txt"
      - "corrupt_msgs=1"
      - "auto_start=1"
    networks:
      router-net:
        ipv4_address: 172.16.238.10
  routed_20:
    build: .
    stdin_open: true
    tty: true
    command:
      - "./routed"
      - "172.16.238.20"
      - "/file_dir"
      - "link_list=/topo/links_20.txt"
      - "corrupt_msgs=1"
      - "auto_start=1"
    networks:
      router-net:
        ipv4_address: 172.16.238.20
  routed_30:
    build: .
    stdin_open: true
    tty: true
    command:
      - "./routed"
      - "172.16.238.30"
      - "/file_dir"
      - "link_list=/topo/links_30.txt"
      - "corrupt_msgs=1"
      - "auto_start=1"
    networks:
      router-net:
        ipv4_address: 172.16.238.30
networks:
  router-net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"