version: "3.7"
services:
  routed_10:
    build: .
    stdin_open: true
    tty: true
    command:
      - "./routed"
      - "172.16.238.10"
      - "/file_dir"
      - "link_list=/topo/links_10.txt"
      - "corrupt_msgs=1"
      - "auto_start=1"
      - "log_file=/out/10.log"
    networks:
      router-net:
        ipv4_address: 172.16.238.10
    volumes:
      - type: bind
        source: ./out
        target: /out
  routed_20:
    build: .
    stdin_open: true
    tty: true
    command:
      - "./routed"
      - "172.16.238.20"
      - "/file_dir"
      - "link_list=/topo/links_20.txt"
      - "corrupt_msgs=1"
      - "auto_start=1"
      - "log_file=/out/20.log"
    networks:
      router-net:
        ipv4_address: 172.16.238.20
    volumes:
      - type: bind
        source: ./out
        target: /out
  routed_30:
    build: .
    stdin_open: true
    tty: true
    command:
      - "./routed"
      - "172.16.238.30"
      - "/file_dir"
      - "link_list=/topo/links_30.txt"
      - "corrupt_msgs=1"
      - "auto_start=1"
      - "log_file=/out/30.log"
    networks:
      router-net:
        ipv4_address: 172.16.238.30
    volumes:
      - type: bind
        source: ./out
        target: /out
networks:
  router-net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"