version: "3.7"
services:
  routed_10:
    build: .
    stdin_open: true
    tty: true
    command:
      - "./routed"
      - "172.16.238.10"
      - "/files"
      - "link_list=/topo/small_10.txt"
      - "corrupt_msgs=1"
      - "auto_start=1"
      - "log_file=/logs/10.log"
    networks:
      router-net:
        ipv4_address: 172.16.238.10
    volumes:
      - type: bind
        source: ./logs
        target: /logs
      - type: bind
        source: ./files/10
        target: /files
  routed_20:
    build: .
    stdin_open: true
    tty: true
    command:
      - "./routed"
      - "172.16.238.20"
      - "/files"
      - "link_list=/topo/small_20.txt"
      - "corrupt_msgs=1"
      - "auto_start=1"
      - "log_file=/logs/20.log"
    networks:
      router-net:
        ipv4_address: 172.16.238.20
    volumes:
      - type: bind
        source: ./logs
        target: /logs
      - type: bind
        source: ./files/20
        target: /files
  routed_30:
    build: .
    stdin_open: true
    tty: true
    command:
      - "./routed"
      - "172.16.238.30"
      - "/files"
      - "link_list=/topo/small_30.txt"
      - "corrupt_msgs=1"
      - "auto_start=1"
      - "log_file=/logs/30.log"
    networks:
      router-net:
        ipv4_address: 172.16.238.30
    volumes:
      - type: bind
        source: ./logs
        target: /logs
      - type: bind
        source: ./files/30
        target: /files
networks:
  router-net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"